# Site settings
name: Emmanuel Omokagbo
email: emmanuel.omokagbo@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, iOS Engineer, Swift, iOS, GoLang, JavaScript, Solidity"
skills: "iOS Engineer"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/emmanuel-omokagbo/
  - title: twitter
    url: https://twitter.com/omokagboEM
  - title: github
    url: https://github.com/omokagbo
  - title: hashnode
    url: https://omokagbo.hashnode.dev
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2eaaf2
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty

theme: jekyll-theme-architect